#!/bin/bash

echo "
 ██ ███████ ██████  ███████ ███████        █████  ███    ███ ██████  ██
██  ██      ██   ██ ██      ██            ██   ██ ████  ████ ██   ██  ██
██  █████   ██████  █████   ███████ █████ ███████ ██ ████ ██ ██   ██  ██
██  ██      ██      ██           ██       ██   ██ ██  ██  ██ ██   ██  ██
 ██ ██      ██      ███████ ███████       ██   ██ ██      ██ ██████  ██

"

echo "Sets up Ubuntu (latest) on any OS that has Docker"

read -p "Are you sure you want to proceed? (y/n): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation aborted."
    exit 1
fi

read -p "Enter hostname (default: ubuntu): " HOSTNAME
HOSTNAME=${HOSTNAME:-ubuntu}

cat <<EOF > Dockerfile
FROM ubuntu:latest

RUN apt-get update
RUN apt-get install nano neofetch curl -y
RUN echo 'root:root' | chpasswd
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
RUN apt-get install -y systemd systemd-sysv dbus dbus-user-session
RUN printf "systemctl start systemd-logind" >> /etc/profile

ENTRYPOINT ["/sbin/init"]
EOF

echo "Installing..."
docker build -t utmp . > /dev/null 2>&1

if [ $? -ne 0 ]; then
    echo "Build failed."
    exit 1
fi

echo "Done installing"

echo "
 ██ ██████  ██    ██ ███    ██ ███    ██ ██ ███    ██  ██████      ██████  ███████ ██
██  ██   ██ ██    ██ ████   ██ ████   ██ ██ ████   ██ ██           ██   ██ ██       ██
██  ██████  ██    ██ ██ ██  ██ ██ ██  ██ ██ ██ ██  ██ ██   ███     ██████  █████    ██
██  ██   ██ ██    ██ ██  ██ ██ ██  ██ ██ ██ ██  ██ ██ ██    ██     ██      ██       ██
 ██ ██   ██  ██████  ██   ████ ██   ████ ██ ██   ████  ██████      ██      ███████ ██

Username: root
Password: root
Hostname: $HOSTNAME
"

docker run -it \
    --privileged \
    --cap-add=ALL \
    --hostname "$HOSTNAME" \
    --name "$HOSTNAME" \
    utmp
